### ISSUE TITLE
This repo should be configured to require scanned commits

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/video-object-detection#2]
Since this repo is being included in the CI system for `veracruz-project/veracruz`, this repo should have stricter restrictions on commits.

Suggestions:
1. require PRs for merges to main
2. restrict pushes directly to main
3. require signed commits

**Comment by gbryant-arm** [comment]
Fixed.
Should we deploy a CI just to make sure the code builds and and runs (standalone, i.e. native and/or WASM outside Veracruz)?

**Comment by gbryant-arm** [comment]
Done in #4
